import Foundation

/// The REAL pending-question payload captured from the live wifi-densepose
/// session via the relay (2026-07-25): 3 questions, 11 options, long Russian
/// texts, one multi-select. This is the payload whose rendering blew the
/// question dock past the screen with no way to scroll or dismiss.
enum QuestionFixtures {
    static let wifiDensepose = #"[{"id":"que_f99ab2933001MZzuSr2q2TYN0r","sessionID":"ses_06658a32dffeTTItm2zRLd77U1","questions":[{"question":"Какие именно у тебя ESP32? От этого зависит, какая прошивка вольётся (оригинальный ESP32 и ESP32-C3 НЕ поддерживаются — одноядрные, не тянут CSI DSP).","header":"Модель ESP32","options":[{"label":"ESP32-S3 (8MB flash)","description":"Рекомендованный target. DevKitC-1 / XIAO ESP32-S3 / SuperMini. Стандартная прошивка 8MB из release_bins/."},{"label":"ESP32-S3 (4MB flash)","description":"Компактные платы с 4MB. Нужен сборка 4mb (esp32-csi-node-4mb.bin)."},{"label":"ESP32-C6","description":"Wi-Fi 6 research target. Сборка под esp32c6 из исходников (idf.py set-target esp32c6)."},{"label":"Не знаю / mixes","description":"Разные или неизвестные — расскажу как проверить chip и flash size через esptool flash_id."}]},{"question":"Где будет работать агрегатор (sensing-server, приём UDP:5005 от ESP32)? ESP32 должны слать на его IP в той же LAN. На этом linux-сервере нет USB и он скорее всего не в твоей домашней сети.","header":"Где работает агрегатор","options":[{"label":"Домашний laptop/RPi в той же WiFi-сети","description":"Рекомендую: ESP32 и агрегатор в одной LAN. Ставим Docker или бинарь sensing-server на laptop/RPi."},{"label":"Этот linux-сервер","description":"Только если он доступен из домашней сети (порт-проброс/VPN). ESP32 шлют UDP на его публичный/VPN IP. Сложнее с NAT/firewall."},{"label":"ESP32 как AP-точки + отдельный хост","description":"ESP32 в режиме soft-AP, хост подключается к ним. Не основной сценарий RuView."}]},{"question":"Что для тебя значит «кто есть и где»? От этого зависит объём работы (прошивка+сервер vs полная калибровка ADR-151 с управляемыми анкерами).","header":"Цель по точности","options":[{"label":"Presence по комнатам","description":"По 1 узлу на комнату → «кто-то в кухне/спальне». Работает на эвристике сразу. Реалистично и честно."},{"label":"Дыхание/пульс/поза","description":"Vitals + posture. Либо эвристики прошивки (Tier 2), либо ADR-151 специалисты после enroll/train."},{"label":"Идентификация «кто именно»","description":"AETHER re-ID. Нужен полный enroll (stand/sit/lie/breathe/move) + train-room per person. Статистика, не биометрия."},{"label":"Координаты (x,y) в комнате","description":"Multistatic mesh + geometry enrollment. В README прямо: 'strongest field peak', не валидированная триангуляция. Ожидания нужно снизить."}],"multiple":true}],"tool":{"messageID":"msg_f99aa9b90001KrP5wJNNvMqlzG","callID":"call_20746c7eb8934376b9999f20"}}]"#
}
